//-----------------------------------------------------------------------------
// Copyright (C) Proxmark3 contributors. See AUTHORS.md for details.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// See LICENSE.txt for the text of the license.
//-----------------------------------------------------------------------------
//
// CRYPTO-1 LFSR engine for FPGA-accelerated MIFARE Classic key recovery.
// Implements the 48-bit LFSR (split into 24-bit odd/even halves),
// the nonlinear filter function, and a state machine for key trial.
//
// Reference: common/crapto1/crapto1.h, common/crapto1/crypto1.c
//-----------------------------------------------------------------------------

module crypto1_engine(
    input clk,                  // 24 MHz (pck0)
    input rst,                  // synchronous reset (active high)
    input ssp_dout,             // serial key data in (ARM -> FPGA)
    output reg ssp_din,         // serial hit data out (FPGA -> ARM)
    output reg ssp_frame,       // frame pulse: high = hit report start
    output reg ssp_clk,         // SSC clock (generated by this module)
    input spi_load,             // pulse high for one clk to latch spi_data
    input [2:0] spi_param_sel,  // which parameter register to load
    input [11:0] spi_data,      // 12-bit SPI data field
    output reg hit,             // high when a matching key is found
    output reg ready            // high when ready to accept next key
);

// ============================================================================
// LFSR feedback polynomials (from crapto1.h)
// ============================================================================
localparam [23:0] LF_POLY_ODD  = 24'h29CE5C;
localparam [23:0] LF_POLY_EVEN = 24'h870804;

// ============================================================================
// State encoding
// ============================================================================
localparam [2:0] S_IDLE            = 3'd0,
                 S_LOAD_KEY        = 3'd1,
                 S_INIT_LFSR       = 3'd2,
                 S_FEED_UID_XOR_NT = 3'd3,
                 S_VERIFY          = 3'd4,
                 S_REPORT_HIT      = 3'd5;

// ============================================================================
// SPI parameter registers
//
// The top-level passes spi_param_sel = shift_reg[14:12], which for SPI
// commands 4-7 (shift_reg[15:14] == 2'b01) yields param_sel values 4-7:
//
//   FPGA_CMD_CRYPTO1_PARAMS     (4<<12) -> param_sel = 4  shift data in
//   FPGA_CMD_CRYPTO1_LATCH_UID  (5<<12) -> param_sel = 5  latch -> uid
//   FPGA_CMD_CRYPTO1_LATCH_NT   (6<<12) -> param_sel = 6  latch -> nt
//   FPGA_CMD_CRYPTO1_LATCH_MISC (7<<12) -> param_sel = 7  latch -> nr/ar/check or trigger
//
// Protocol for loading a 32-bit parameter:
//   1. Send 3x FPGA_CMD_CRYPTO1_PARAMS with 12-bit data chunks (MSB first)
//      to shift them into param_shift accumulator.
//   2. Send the appropriate latch command to copy param_shift to the target:
//      - LATCH_UID:  param_shift -> uid
//      - LATCH_NT:   param_shift -> nt
//      - LATCH_MISC: param_shift -> register selected by spi_data[2:0]:
//                     0 = nr, 1 = ar, 2 = check_data
//
// To trigger the engine:
//   Send FPGA_CMD_CRYPTO1_LATCH_MISC with spi_data[3] = 1
// ============================================================================
reg [31:0] param_shift;
reg [31:0] uid;
reg [31:0] nt;
reg [31:0] nr;
reg [31:0] ar;
reg [31:0] check_data;

always @(posedge clk) begin
    if (rst) begin
        param_shift <= 32'd0;
        uid        <= 32'd0;
        nt         <= 32'd0;
        nr         <= 32'd0;
        ar         <= 32'd0;
        check_data <= 32'd0;
    end else if (spi_load) begin
        case (spi_param_sel)
            3'd4: param_shift <= {param_shift[19:0], spi_data};  // shift in
            3'd5: uid        <= param_shift;                      // latch UID
            3'd6: nt         <= param_shift;                      // latch NT
            3'd7: begin                                           // latch misc
                if (!spi_data[3]) begin  // data[3]=1 is trigger, not latch
                    case (spi_data[2:0])
                        3'd0: nr         <= param_shift;
                        3'd1: ar         <= param_shift;
                        3'd2: check_data <= param_shift;
                        default: ;
                    endcase
                end
            end
            default: ;
        endcase
    end
end

// ============================================================================
// Start trigger: on LATCH_MISC (param_sel=7) with spi_data[3] set
// ============================================================================
reg start_trigger;
always @(posedge clk) begin
    if (rst)
        start_trigger <= 1'b0;
    else if (spi_load && spi_param_sel == 3'd7 && spi_data[3])
        start_trigger <= 1'b1;
    else if (state != S_IDLE)
        start_trigger <= 1'b0;
end

// ============================================================================
// LFSR state
// ============================================================================
reg [23:0] lfsr_odd;
reg [23:0] lfsr_even;

// ============================================================================
// Nonlinear filter function
//
// Exact translation of the C implementation from crapto1.h:
//
//   f  = 0xf22c0 >> (x       & 0xf) & 16;   // extract bit 4
//   f |= 0x6c9c0 >> (x >>  4 & 0xf) &  8;   // extract bit 3
//   f |= 0x3c8b0 >> (x >>  8 & 0xf) &  4;   // extract bit 2
//   f |= 0x1e458 >> (x >> 12 & 0xf) &  2;   // extract bit 1
//   f |= 0x0d938 >> (x >> 16 & 0xf) &  1;   // extract bit 0
//   return BIT(0xEC57E80A, f);
//
// Derivation: "(C >> nibble) & (1 << k)" extracts bit (nibble + k) of C.
// Dividing each constant by 2^k gives a 16-bit LUT indexed by the nibble:
//   f[4] = (0xf22c0 >> 4)[x[3:0]]   = 0xF22C[x[3:0]]
//   f[3] = (0x6c9c0 >> 3)[x[7:4]]   = 0xD938[x[7:4]]
//   f[2] = (0x3c8b0 >> 2)[x[11:8]]  = 0xF22C[x[11:8]]
//   f[1] = (0x1e458 >> 1)[x[15:12]] = 0xF22C[x[15:12]]
//   f[0] = (0x0d938 >> 0)[x[19:16]] = 0xD938[x[19:16]]
//
// Verification: 0xf22c0 >> 4 = 0xF22C, 0x6c9c0 >> 3 = 0xD938,
//   0x3c8b0 >> 2 = 0xF22C, 0x1e458 >> 1 = 0xF22C, 0x0d938 = 0xD938.
// ============================================================================

function filter;
    input [23:0] x;
    reg [4:0] f;
    begin
        f[4] = (16'hF22C >> x[3:0])   & 1'b1;
        f[3] = (16'hD938 >> x[7:4])   & 1'b1;
        f[2] = (16'hF22C >> x[11:8])  & 1'b1;
        f[1] = (16'hF22C >> x[15:12]) & 1'b1;
        f[0] = (16'hD938 >> x[19:16]) & 1'b1;
        filter = (32'hEC57E80A >> f) & 1'b1;
    end
endfunction

wire filter_out = filter(lfsr_odd);

// ============================================================================
// crypto1_bit — LFSR step logic (combinational)
//
// C code:
//   ret = filter(s->odd);
//   feedin  = ret & (!!is_encrypted);
//   feedin ^= !!in;
//   feedin ^= LF_POLY_ODD & s->odd;
//   feedin ^= LF_POLY_EVEN & s->even;
//   s->even = s->even << 1 | evenparity32(feedin);
//   t = s->odd; s->odd = s->even; s->even = t;
//
// The C builds feedin as a uint32_t via XOR, then takes evenparity32.
// Since evenparity32 = XOR-reduction, and XOR-reduction distributes
// over XOR, we get:
//   new_bit = ^(LF_POLY_ODD & odd) ^ ^(LF_POLY_EVEN & even)
//           ^ (filter_out & is_encrypted) ^ in_bit
//
// After the step:
//   odd  <= {even[22:0], new_bit}   (even shifted left with new_bit, then swapped into odd)
//   even <= odd                     (old odd becomes new even)
// ============================================================================

// Combinational input bit mux — avoids one-cycle pipeline delay that would
// occur if input_bit were a register assigned in the same always block.
reg [2:0]  state;
reg [5:0]  bit_counter;
reg [47:0] key_shift;
reg [31:0] uid_xor_nt;
reg        is_encrypted;

wire [4:0] bebit_idx = bit_counter[4:0] ^ 5'd24;

// new_even_lsb is computed per-state inside the always block.
// This avoids timing issues with combinational dependencies on
// state/bit_counter that are updated by NBA in the same block.
reg new_even_lsb_r;  // registered: computed in always block, used for LFSR step
wire poly_parity = ^(LF_POLY_ODD & lfsr_odd) ^ ^(LF_POLY_EVEN & lfsr_even);

// ============================================================================
// Key initialization bit mapping
//
// C code (crypto1_init):
//   for (int i = 47; i > 0; i -= 2) {
//       odd  = odd  << 1 | BIT(key, (i - 1) ^ 7);
//       even = even << 1 | BIT(key, i ^ 7);
//   }
//
// 24 iterations: k = 0..23, i = 47 - 2*k
//   odd[23-k]  = key[(46 - 2*k) ^ 7]
//   even[23-k] = key[(47 - 2*k) ^ 7]
//
// The ^7 operation flips bits [2:0] of the index, which reverses bit
// order within each byte of the key. This accounts for the byte/bit
// ordering convention used by the MIFARE Classic protocol.
//
// We compute the key bit indices on the fly from bit_counter.
// ============================================================================
wire [5:0] init_i       = 6'd47 - {bit_counter[4:0], 1'b0};
wire [5:0] key_idx_even = init_i ^ 6'd7;
wire [5:0] key_idx_odd  = (init_i - 6'd1) ^ 6'd7;

// ============================================================================
// SSC clock generation: divide 24 MHz by 4 -> 6 MHz
// ============================================================================
reg [1:0] ssc_div;
always @(posedge clk) begin
    if (rst)
        ssc_div <= 2'd0;
    else
        ssc_div <= ssc_div + 2'd1;
end

wire ssc_clk_rising = (ssc_div == 2'd1);

always @(posedge clk) begin
    if (rst)
        ssp_clk <= 1'b0;
    else if (ssc_div == 2'd1)
        ssp_clk <= 1'b1;
    else if (ssc_div == 2'd3)
        ssp_clk <= 1'b0;
end

// ============================================================================
// Keystream collection and early termination
// ============================================================================
reg [31:0] ks_collected;

// For early termination, we check after every 8 bits whether the keystream
// collected so far matches the corresponding bits of check_data.
// ks_collected is shifted left, so bit 0 is the most recent.
// After n bits, ks_collected[n-1:0] contains the keystream, with [n-1]
// being the first bit and [0] the most recent.
//
// We compare against check_data which is organized the same way (MSB first).
// After 8 bits: ks_collected[7:0] vs check_data[31:24]
// After 16 bits: ks_collected[7:0] vs check_data[23:16]
// etc.
//
// For early termination we check byte-by-byte as we go.

wire [7:0] ks_byte = {ks_collected[6:0], filter_out};  // current byte being formed

// Which check_data byte to compare against, based on how many bytes done
wire [7:0] check_byte =
    (bit_counter[5:3] == 3'd0) ? check_data[31:24] :
    (bit_counter[5:3] == 3'd1) ? check_data[23:16] :
    (bit_counter[5:3] == 3'd2) ? check_data[15:8]  :
    (bit_counter[5:3] == 3'd3) ? check_data[7:0]   :
    (bit_counter[5:3] == 3'd4) ? check_data[31:24] :  // second word if needed
    8'd0;

// ============================================================================
// Main state machine
// ============================================================================
always @(posedge clk) begin
    if (rst) begin
        state        <= S_IDLE;
        bit_counter  <= 6'd0;
        key_shift    <= 48'd0;
        lfsr_odd     <= 24'd0;
        lfsr_even    <= 24'd0;
        uid_xor_nt   <= 32'd0;
        is_encrypted <= 1'b0;
        ks_collected <= 32'd0;
        hit          <= 1'b0;
        ready        <= 1'b1;
        ssp_din      <= 1'b0;
        ssp_frame    <= 1'b0;
    end else begin
        // Default: deassert frame pulse each cycle
        ssp_frame <= 1'b0;

        case (state)

            // ==============================================================
            S_IDLE: begin
                ready <= 1'b1;
                hit   <= 1'b0;
                if (start_trigger) begin
                    state       <= S_LOAD_KEY;
                    bit_counter <= 6'd0;
                    ready       <= 1'b0;
                    uid_xor_nt  <= uid ^ nt;
                end
            end

            // ==============================================================
            // Load 48-bit key via SSC serial input, MSB first.
            // ==============================================================
            S_LOAD_KEY: begin
                if (ssc_clk_rising) begin
                    key_shift   <= {key_shift[46:0], ssp_dout};
                    bit_counter <= bit_counter + 6'd1;
                    if (bit_counter == 6'd47) begin
                        state       <= S_INIT_LFSR;
                        bit_counter <= 6'd0;
                        lfsr_odd    <= 24'd0;
                        lfsr_even   <= 24'd0;
                    end
                end
            end

            // ==============================================================
            // Initialize LFSR from key using crypto1_init bit mapping.
            // 24 iterations at full clock speed.
            // ==============================================================
            S_INIT_LFSR: begin
                lfsr_odd  <= {lfsr_odd[22:0],  key_shift[key_idx_odd]};
                lfsr_even <= {lfsr_even[22:0], key_shift[key_idx_even]};
                bit_counter <= bit_counter + 6'd1;
                if (bit_counter == 6'd23) begin
                    state        <= S_FEED_UID_XOR_NT;
                    bit_counter  <= 6'd0;
                    is_encrypted <= 1'b0;
                end
            end

            // ==============================================================
            // Feed UID^NT (32 bits) with is_encrypted = 0.
            // One crypto1_bit step per clock cycle.
            // cur_input_bit is combinationally driven from uid_xor_nt.
            // ==============================================================
            S_FEED_UID_XOR_NT: begin
                // Compute new_even_lsb with FEED input (not encrypted)
                new_even_lsb_r = poly_parity ^ uid_xor_nt[bebit_idx];
                lfsr_odd  <= {lfsr_even[22:0], new_even_lsb_r};
                lfsr_even <= lfsr_odd;
                bit_counter <= bit_counter + 6'd1;
                if (bit_counter == 6'd31) begin
                    state        <= S_VERIFY;
                    bit_counter  <= 6'd0;
                    ks_collected <= 32'd0;
                    is_encrypted <= 1'b1;
                end
            end

            // ==============================================================
            // Verify phase: feed NR||AR (64 bits total) with is_encrypted=1,
            // collecting keystream bits. Compare against check_data with
            // early termination on byte mismatch.
            //
            // bit_counter 0..31:  feed NR bits, collect keystream
            // bit_counter 32..63: feed AR bits, collect keystream
            //
            // We compare the first 32 keystream bits (from NR phase) against
            // check_data. Early termination checks after each byte.
            // ==============================================================
            S_VERIFY: begin
                // Collect keystream bit (filter_out BEFORE this step)
                ks_collected <= {ks_collected[30:0], filter_out};

                // Compute new_even_lsb with VERIFY input (encrypted)
                // Input bit comes from NR (bc < 32) or AR (bc >= 32)
                if (bit_counter < 6'd32)
                    new_even_lsb_r = poly_parity ^ filter_out ^ nr[bit_counter[4:0] ^ 5'd24];
                else
                    new_even_lsb_r = poly_parity ^ filter_out ^ ar[bit_counter[4:0] ^ 5'd24];

                // Advance LFSR
                lfsr_odd  <= {lfsr_even[22:0], new_even_lsb_r};
                lfsr_even <= lfsr_odd;

                bit_counter <= bit_counter + 6'd1;

                // Early termination: check after each complete byte
                if (bit_counter[2:0] == 3'd7 && bit_counter < 6'd32) begin
                    if (ks_byte != check_byte) begin
                        state       <= S_IDLE;
                        bit_counter <= 6'd0;
                    end
                end

                // Final check at bit 31 (end of NR phase, 32 keystream bits)
                if (bit_counter == 6'd31) begin
                    if (ks_byte == check_byte) begin
                        state <= S_REPORT_HIT;
                        hit   <= 1'b1;
                    end else begin
                        state <= S_IDLE;
                    end
                    bit_counter <= 6'd0;
                end
            end

            // ==============================================================
            // Report hit: shift out the 48-bit key via SSC, MSB first.
            // Assert ssp_frame for the first bit.
            // ==============================================================
            S_REPORT_HIT: begin
                if (ssc_clk_rising) begin
                    ssp_frame <= (bit_counter == 6'd0);
                    ssp_din   <= key_shift[6'd47 - bit_counter];
                    bit_counter <= bit_counter + 6'd1;

                    if (bit_counter == 6'd47) begin
                        state       <= S_IDLE;
                        bit_counter <= 6'd0;
                    end
                end
            end

            default: state <= S_IDLE;

        endcase
    end
end

endmodule
