//-----------------------------------------------------------------------------
// Copyright (C) Proxmark3 contributors. See AUTHORS.md for details.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// See LICENSE.txt for the text of the license.
//-----------------------------------------------------------------------------
//
// CRYPTO-1 LFSR engine for FPGA-accelerated MIFARE Classic key recovery.
// Implements the 48-bit LFSR (split into 24-bit odd/even halves),
// the nonlinear filter function, and a state machine for key trial.
//
// Reference: common/crapto1/crapto1.h, common/crapto1/crypto1.c
//-----------------------------------------------------------------------------

module crypto1_engine(
    input clk,                  // 24 MHz (pck0)
    input rst,                  // synchronous reset (active high)
    input ssp_dout,             // serial key data in (ARM -> FPGA)
    output reg ssp_din,         // serial hit data out (FPGA -> ARM)
    output reg ssp_frame,       // frame pulse: high = hit report start
    output reg ssp_clk,         // SSC clock (generated by this module)
    input spi_load,             // pulse high for one clk to latch spi_data
    input [2:0] spi_param_sel,  // which parameter register to load
    input [11:0] spi_data,      // 12-bit SPI data field
    output reg hit,             // high when a matching key is found
    output reg ready            // high when ready to accept next key
);

// ============================================================================
// LFSR feedback polynomials (from crapto1.h)
// ============================================================================
localparam [23:0] LF_POLY_ODD  = 24'h29CE5C;
localparam [23:0] LF_POLY_EVEN = 24'h870804;

// ============================================================================
// State encoding
// ============================================================================
localparam [2:0] S_IDLE            = 3'd0,
                 S_LOAD_KEY        = 3'd1,
                 S_INIT_LFSR       = 3'd2,
                 S_FEED_UID_XOR_NT = 3'd3,
                 S_VERIFY          = 3'd4,
                 S_REPORT_HIT      = 3'd5;

// ============================================================================
// SPI parameter registers
//
// The ARM loads 32-bit values through 12-bit SPI writes. Each param_sel
// targets a specific register using a shift-in scheme: writing to a
// param_sel shifts that register left by 12 and ORs in the new data.
// Three writes of 12 bits = 36 bits capacity (top 4 bits ignored for 32-bit
// values). The ARM writes MSB-first, 3 times per 32-bit parameter.
//
// param_sel 0: UID
// param_sel 1: NT
// param_sel 2: NR
// param_sel 3: AR
// param_sel 4: check_data (expected keystream for verification)
// param_sel 5: config (bit 0 = start trigger)
// param_sel 6-7: reserved
// ============================================================================
reg [31:0] uid;
reg [31:0] nt;
reg [31:0] nr;
reg [31:0] ar;
reg [31:0] check_data;

always @(posedge clk) begin
    if (rst) begin
        uid        <= 32'd0;
        nt         <= 32'd0;
        nr         <= 32'd0;
        ar         <= 32'd0;
        check_data <= 32'd0;
    end else if (spi_load) begin
        case (spi_param_sel)
            3'd0: uid        <= {uid[19:0], spi_data};
            3'd1: nt         <= {nt[19:0], spi_data};
            3'd2: nr         <= {nr[19:0], spi_data};
            3'd3: ar         <= {ar[19:0], spi_data};
            3'd4: check_data <= {check_data[19:0], spi_data};
            default: ;
        endcase
    end
end

// ============================================================================
// Start trigger: latch on SPI write to param_sel 5 with data bit 0 set
// ============================================================================
reg start_trigger;
always @(posedge clk) begin
    if (rst)
        start_trigger <= 1'b0;
    else if (spi_load && spi_param_sel == 3'd5 && spi_data[0])
        start_trigger <= 1'b1;
    else if (state != S_IDLE)
        start_trigger <= 1'b0;
end

// ============================================================================
// LFSR state
// ============================================================================
reg [23:0] lfsr_odd;
reg [23:0] lfsr_even;

// ============================================================================
// Nonlinear filter function
//
// Exact translation of the C implementation from crapto1.h:
//
//   f  = 0xf22c0 >> (x       & 0xf) & 16;   // extract bit 4
//   f |= 0x6c9c0 >> (x >>  4 & 0xf) &  8;   // extract bit 3
//   f |= 0x3c8b0 >> (x >>  8 & 0xf) &  4;   // extract bit 2
//   f |= 0x1e458 >> (x >> 12 & 0xf) &  2;   // extract bit 1
//   f |= 0x0d938 >> (x >> 16 & 0xf) &  1;   // extract bit 0
//   return BIT(0xEC57E80A, f);
//
// Derivation: "(C >> nibble) & (1 << k)" extracts bit (nibble + k) of C.
// Dividing each constant by 2^k gives a 16-bit LUT indexed by the nibble:
//   f[4] = (0xf22c0 >> 4)[x[3:0]]   = 0xF22C[x[3:0]]
//   f[3] = (0x6c9c0 >> 3)[x[7:4]]   = 0xD938[x[7:4]]
//   f[2] = (0x3c8b0 >> 2)[x[11:8]]  = 0xF22C[x[11:8]]
//   f[1] = (0x1e458 >> 1)[x[15:12]] = 0xF22C[x[15:12]]
//   f[0] = (0x0d938 >> 0)[x[19:16]] = 0xD938[x[19:16]]
//
// Verification: 0xf22c0 >> 4 = 0xF22C, 0x6c9c0 >> 3 = 0xD938,
//   0x3c8b0 >> 2 = 0xF22C, 0x1e458 >> 1 = 0xF22C, 0x0d938 = 0xD938.
// ============================================================================

function filter;
    input [23:0] x;
    reg [4:0] f;
    begin
        f[4] = (16'hF22C >> x[3:0])   & 1'b1;
        f[3] = (16'hD938 >> x[7:4])   & 1'b1;
        f[2] = (16'hF22C >> x[11:8])  & 1'b1;
        f[1] = (16'hF22C >> x[15:12]) & 1'b1;
        f[0] = (16'hD938 >> x[19:16]) & 1'b1;
        filter = (32'hEC57E80A >> f) & 1'b1;
    end
endfunction

wire filter_out = filter(lfsr_odd);

// ============================================================================
// crypto1_bit — LFSR step logic (combinational)
//
// C code:
//   ret = filter(s->odd);
//   feedin  = ret & (!!is_encrypted);
//   feedin ^= !!in;
//   feedin ^= LF_POLY_ODD & s->odd;
//   feedin ^= LF_POLY_EVEN & s->even;
//   s->even = s->even << 1 | evenparity32(feedin);
//   t = s->odd; s->odd = s->even; s->even = t;
//
// The C builds feedin as a uint32_t via XOR, then takes evenparity32.
// Since evenparity32 = XOR-reduction, and XOR-reduction distributes
// over XOR, we get:
//   new_bit = ^(LF_POLY_ODD & odd) ^ ^(LF_POLY_EVEN & even)
//           ^ (filter_out & is_encrypted) ^ in_bit
//
// After the step:
//   odd  <= {even[22:0], new_bit}   (even shifted left with new_bit, then swapped into odd)
//   even <= odd                     (old odd becomes new even)
// ============================================================================

// Combinational input bit mux — avoids one-cycle pipeline delay that would
// occur if input_bit were a register assigned in the same always block.
reg [2:0]  state;
reg [5:0]  bit_counter;
reg [47:0] key_shift;
reg [31:0] uid_xor_nt;
reg        is_encrypted;

wire [4:0] bebit_idx = bit_counter[4:0] ^ 5'd24;

// Select the correct input bit based on current state and bit_counter
reg cur_input_bit;
always @(*) begin
    case (state)
        S_FEED_UID_XOR_NT: cur_input_bit = uid_xor_nt[bebit_idx];
        S_VERIFY: begin
            if (bit_counter < 6'd32)
                cur_input_bit = nr[bit_counter[4:0] ^ 5'd24];
            else
                cur_input_bit = ar[bit_counter[4:0] ^ 5'd24];
        end
        default: cur_input_bit = 1'b0;
    endcase
end

wire new_even_lsb = ^(LF_POLY_ODD & lfsr_odd)
                  ^ ^(LF_POLY_EVEN & lfsr_even)
                  ^ (filter_out & is_encrypted)
                  ^ cur_input_bit;

// ============================================================================
// Key initialization bit mapping
//
// C code (crypto1_init):
//   for (int i = 47; i > 0; i -= 2) {
//       odd  = odd  << 1 | BIT(key, (i - 1) ^ 7);
//       even = even << 1 | BIT(key, i ^ 7);
//   }
//
// 24 iterations: k = 0..23, i = 47 - 2*k
//   odd[23-k]  = key[(46 - 2*k) ^ 7]
//   even[23-k] = key[(47 - 2*k) ^ 7]
//
// The ^7 operation flips bits [2:0] of the index, which reverses bit
// order within each byte of the key. This accounts for the byte/bit
// ordering convention used by the MIFARE Classic protocol.
//
// We compute the key bit indices on the fly from bit_counter.
// ============================================================================
wire [5:0] init_i       = 6'd47 - {bit_counter[4:0], 1'b0};
wire [5:0] key_idx_even = init_i ^ 6'd7;
wire [5:0] key_idx_odd  = (init_i - 6'd1) ^ 6'd7;

// ============================================================================
// SSC clock generation: divide 24 MHz by 4 -> 6 MHz
// ============================================================================
reg [1:0] ssc_div;
always @(posedge clk) begin
    if (rst)
        ssc_div <= 2'd0;
    else
        ssc_div <= ssc_div + 2'd1;
end

wire ssc_clk_rising = (ssc_div == 2'd1);

always @(posedge clk) begin
    if (rst)
        ssp_clk <= 1'b0;
    else if (ssc_div == 2'd1)
        ssp_clk <= 1'b1;
    else if (ssc_div == 2'd3)
        ssp_clk <= 1'b0;
end

// ============================================================================
// Keystream collection and early termination
// ============================================================================
reg [31:0] ks_collected;

// For early termination, we check after every 8 bits whether the keystream
// collected so far matches the corresponding bits of check_data.
// ks_collected is shifted left, so bit 0 is the most recent.
// After n bits, ks_collected[n-1:0] contains the keystream, with [n-1]
// being the first bit and [0] the most recent.
//
// We compare against check_data which is organized the same way (MSB first).
// After 8 bits: ks_collected[7:0] vs check_data[31:24]
// After 16 bits: ks_collected[7:0] vs check_data[23:16]
// etc.
//
// For early termination we check byte-by-byte as we go.

wire [7:0] ks_byte = {ks_collected[6:0], filter_out};  // current byte being formed

// Which check_data byte to compare against, based on how many bytes done
wire [7:0] check_byte =
    (bit_counter[5:3] == 3'd0) ? check_data[31:24] :
    (bit_counter[5:3] == 3'd1) ? check_data[23:16] :
    (bit_counter[5:3] == 3'd2) ? check_data[15:8]  :
    (bit_counter[5:3] == 3'd3) ? check_data[7:0]   :
    (bit_counter[5:3] == 3'd4) ? check_data[31:24] :  // second word if needed
    8'd0;

// ============================================================================
// Main state machine
// ============================================================================
always @(posedge clk) begin
    if (rst) begin
        state        <= S_IDLE;
        bit_counter  <= 6'd0;
        key_shift    <= 48'd0;
        lfsr_odd     <= 24'd0;
        lfsr_even    <= 24'd0;
        uid_xor_nt   <= 32'd0;
        is_encrypted <= 1'b0;
        ks_collected <= 32'd0;
        hit          <= 1'b0;
        ready        <= 1'b1;
        ssp_din      <= 1'b0;
        ssp_frame    <= 1'b0;
    end else begin
        // Default: deassert frame pulse each cycle
        ssp_frame <= 1'b0;

        case (state)

            // ==============================================================
            S_IDLE: begin
                ready <= 1'b1;
                hit   <= 1'b0;
                if (start_trigger) begin
                    state       <= S_LOAD_KEY;
                    bit_counter <= 6'd0;
                    ready       <= 1'b0;
                    uid_xor_nt  <= uid ^ nt;
                end
            end

            // ==============================================================
            // Load 48-bit key via SSC serial input, MSB first.
            // ==============================================================
            S_LOAD_KEY: begin
                if (ssc_clk_rising) begin
                    key_shift   <= {key_shift[46:0], ssp_dout};
                    bit_counter <= bit_counter + 6'd1;
                    if (bit_counter == 6'd47) begin
                        state       <= S_INIT_LFSR;
                        bit_counter <= 6'd0;
                        lfsr_odd    <= 24'd0;
                        lfsr_even   <= 24'd0;
                    end
                end
            end

            // ==============================================================
            // Initialize LFSR from key using crypto1_init bit mapping.
            // 24 iterations at full clock speed.
            // ==============================================================
            S_INIT_LFSR: begin
                lfsr_odd  <= {lfsr_odd[22:0],  key_shift[key_idx_odd]};
                lfsr_even <= {lfsr_even[22:0], key_shift[key_idx_even]};
                bit_counter <= bit_counter + 6'd1;
                if (bit_counter == 6'd23) begin
                    state        <= S_FEED_UID_XOR_NT;
                    bit_counter  <= 6'd0;
                    is_encrypted <= 1'b0;
                end
            end

            // ==============================================================
            // Feed UID^NT (32 bits) with is_encrypted = 0.
            // One crypto1_bit step per clock cycle.
            // cur_input_bit is combinationally driven from uid_xor_nt.
            // ==============================================================
            S_FEED_UID_XOR_NT: begin
                lfsr_odd  <= {lfsr_even[22:0], new_even_lsb};
                lfsr_even <= lfsr_odd;

                bit_counter <= bit_counter + 6'd1;
                if (bit_counter == 6'd31) begin
                    state        <= S_VERIFY;
                    bit_counter  <= 6'd0;
                    ks_collected <= 32'd0;
                    is_encrypted <= 1'b1;
                end
            end

            // ==============================================================
            // Verify phase: feed NR||AR (64 bits total) with is_encrypted=1,
            // collecting keystream bits. Compare against check_data with
            // early termination on byte mismatch.
            //
            // bit_counter 0..31:  feed NR bits, collect keystream
            // bit_counter 32..63: feed AR bits, collect keystream
            //
            // We compare the first 32 keystream bits (from NR phase) against
            // check_data. Early termination checks after each byte.
            // ==============================================================
            S_VERIFY: begin
                // Collect keystream bit (filter_out BEFORE this step)
                ks_collected <= {ks_collected[30:0], filter_out};

                // Advance LFSR
                lfsr_odd  <= {lfsr_even[22:0], new_even_lsb};
                lfsr_even <= lfsr_odd;

                bit_counter <= bit_counter + 6'd1;

                // Early termination: check after each complete byte
                if (bit_counter[2:0] == 3'd7 && bit_counter < 6'd32) begin
                    if (ks_byte != check_byte) begin
                        state       <= S_IDLE;
                        bit_counter <= 6'd0;
                    end
                end

                // Final check at bit 31 (end of NR phase, 32 keystream bits)
                if (bit_counter == 6'd31) begin
                    if (ks_byte == check_byte) begin
                        state <= S_REPORT_HIT;
                        hit   <= 1'b1;
                    end else begin
                        state <= S_IDLE;
                    end
                    bit_counter <= 6'd0;
                end
            end

            // ==============================================================
            // Report hit: shift out the 48-bit key via SSC, MSB first.
            // Assert ssp_frame for the first bit.
            // ==============================================================
            S_REPORT_HIT: begin
                if (ssc_clk_rising) begin
                    ssp_frame <= (bit_counter == 6'd0);
                    ssp_din   <= key_shift[6'd47 - bit_counter];
                    bit_counter <= bit_counter + 6'd1;

                    if (bit_counter == 6'd47) begin
                        state       <= S_IDLE;
                        bit_counter <= 6'd0;
                    end
                end
            end

            default: state <= S_IDLE;

        endcase
    end
end

endmodule
